# Generated by Django 4.1.13 on 2024-04-22 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image_product_price_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approver',
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('plus_points', models.IntegerField(default=0)),
                ('minus_points', models.IntegerField(default=0)),
                ('old_points', models.IntegerField(default=0)),
                ('new_points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
