# Generated by Django 4.1.13 on 2024-04-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
